import java.util.Properties
import java.io.FileInputStream

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

// ---------------------------------------------------------------------------
// Release signing.
//
// Foolproof design: the release signing config is driven by an optional
// `keystore.properties` file at the project root. When that file is absent, the
// build falls back to:
//   1. an environment-variable supplied keystore, or
//   2. a well-known `dylandos-release.jks` generated by the provided scripts
//      (scripts/generate-keystore.ps1 / .sh), or
//   3. the Android debug keystore so the release task NEVER fails to produce an
//      APK during development.
//
// For a *production* signed release you should supply a real keystore. The
// provided `build-signed-apk` scripts automate the whole flow (generate keystore
// if missing -> assembleFirestickRelease -> copy APK to android/dist).
// ---------------------------------------------------------------------------
val keystorePropertiesFile = rootProject.file("keystore.properties")
val keystoreProperties = Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

fun prop(name: String, env: String, default: String): String =
    (keystoreProperties[name] as? String)
        ?: System.getenv(env)
        ?: default

// Resolved relative to the project root (android/) so it matches the path the
// build scripts write into keystore.properties. Absolute paths are used as-is.
val releaseStoreFile = rootProject.file(
    prop("storeFile", "KEYSTORE_PATH", "app/dylandos-release.jks")
)

android {
    namespace = "com.dylandos.iptv"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.dylandos.iptv.ultimate"
        minSdk = 23
        targetSdk = 35
        versionCode = 1
        versionName = "1.0.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
        // DYLANDOS IPTV ULTIMATE is a FireStick-first application.
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64")
        }
    }

    signingConfigs {
        create("release") {
            keyAlias = prop("keyAlias", "KEY_ALIAS", "dylandos")
            keyPassword = prop("keyPassword", "KEY_PASSWORD", "dylandos2026")
            storePassword = prop("storePassword", "STORE_PASSWORD", "dylandos2026")
            storeFile = releaseStoreFile
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            // If a release keystore is present, sign the APK. Otherwise fall back
            // to the debug keystore so the task always succeeds during dev.
            if (releaseStoreFile.exists()) {
                signingConfig = signingConfigs.getByName("release")
            } else {
                signingConfig = signingConfigs.getByName("debug")
            }
            // LTO + R8 keep rules for native media engines.
        }
        debug {
            isMinifyEnabled = false
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }

    // Primary flavor dimension. Firestick is the flagship target and is declared
    // first so it is the default choice in Android Studio's Build Variants panel.
    flavorDimensions += "device"
    productFlavors {
        create("Firestick") {
            dimension = "device"
            versionNameSuffix = "-firestick"
            buildConfigField("int", "TARGET_MEMORY_MB", "2048")
            // FireStick 4K / 4K Max are ARMv8; armeabi-v7a kept for legacy sticks.
            ndk {
                abiFilters += listOf("arm64-v8a", "armeabi-v7a")
            }
        }
        create("Generic") {
            dimension = "device"
            versionNameSuffix = "-generic"
            buildConfigField("int", "TARGET_MEMORY_MB", "4096")
            // Include x86_64 for Windows/Mac emulator testing.
            ndk {
                abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "/META-INF/DEPENDENCIES"
            excludes += "META-INF/INDEX.LIST"
        }
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
    arg("room.incremental", "true")
}

dependencies {
    // Core
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.activity.compose)

    // Lifecycle + ViewModel
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)

    // Compose + TV material
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons)
    implementation(libs.androidx.tv.material)
    implementation(libs.androidx.tv.foundation)
    debugImplementation(libs.androidx.compose.ui.tooling)

    // Room
    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    // Paging 3
    implementation(libs.androidx.paging.runtime)
    implementation(libs.androidx.paging.compose)

    // WorkManager
    implementation(libs.androidx.work.runtime)

    // DataStore
    implementation(libs.androidx.datastore)

    // Hilt
    implementation(libs.hilt.android)
    implementation(libs.hilt.work)
    ksp(libs.hilt.compiler)
    ksp(libs.hilt.compiler.work)

    // Coroutines
    implementation(libs.kotlinx.coroutines.android)

    // Coil image loading
    implementation(libs.coil.compose)

    // Native media engines
    implementation(libs.libvlc)
    implementation(libs.mpv)

    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")
}
